<<<<<<< HEAD
# Local MySQL dev
spring.datasource.url=jdbc:mysql://localhost:3306/ksp_pavers
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# H2 Console (optional, only for local tests)
spring.h2.console.enabled=true
=======
# Local MySQL dev
spring.datasource.url=jdbc:mysql://localhost:3306/ksp_pavers
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# H2 Console (optional, only for local tests)
spring.h2.console.enabled=true
>>>>>>> 21f175a2d7df3dd6d9d732ae4c6d5b97313d4a60
spring.h2.console.path=/h2-console