# === RENDER PRODUCTION (PostgreSQL) ===
spring.datasource.url=${postgresql://ksp_user:RddBtZsoP9LveykmUBpJZGooQNSEWOnC@dpg-d7chrgcvikkc738lpbng-a/ksp_pavers}
spring.datasource.username=${ksp_user}
spring.datasource.password=${RddBtZsoP9LveykmUBpJZGooQNSEWOnC}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.h2.console.enabled=false
spring.jpa.hibernate.ddl-auto=update

# Hikari fixes
spring.datasource.hikari.connection-timeout=60000
spring.datasource.hikari.initialization-fail-timeout=0
