# === RENDER PRODUCTION (PostgreSQL) ===
spring.datasource.url=${postgresql://ksp_db_ec07_user:U29OWjjvmWkzXql1R60z7ZzP48Xp4ZJf@dpg-d7btthh17lss73asds40-a/ksp_db_ec07}
spring.datasource.username=${ksp_db_ec07_user}
spring.datasource.password=${U29OWjjvmWkzXql1R60z7ZzP48Xp4ZJf}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.h2.console.enabled=false
spring.jpa.hibernate.ddl-auto=update