# Render Production Database
spring.datasource.url=jdbc:postgresql://dpg-d7chrgcvikkc738lpbng-a.ohio-postgres.render.com:5432/ksp_pavers?user=ksp_user&password=RddBtZsoP9LveykmUBpJZGooQNSEWOnC
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Render Port (CRITICAL)
server.port=${PORT:10000}

# Hikari Connection Pool
spring.datasource.hikari.connection-timeout=60000
spring.datasource.hikari.initialization-fail-timeout=0